servers:
  my-server:
    types:
      bf2demo:
        location: /home/me/my-server/bf2demos/
        uploadPath: bf2demos
      prdemo:
        location: /home/me/my-server/prdemos/
        uploadPath: prdemos
      summary:
        location: /home/me/my-server/summaries/
        uploadPath: summaries

    upload:
      scp:
        address: someserver.com
        username: remoteuser
        privateKeyFile: /home/me/.ssh/id_rsa
        basePath: /var/www/my-server

    discord:
      channelID: "123456789012345678"
      urls:
        bf2demo: https://my-server.com/bf2demos/%s
        prdemo: https://my-server.com/prdemos/%s
        tracker: https://tracker.my-server.com/replay/%s

  my-server-2:
    types:
      bf2demo:
        location: /home/me/my-server-2/bf2demos/
        uploadPath: bf2demos
      prdemo:
        location: /home/me/my-server-2/prdemos/
        uploadPath: prdemos
      summary:
        location: /home/me/my-serve-2r/summaries/
        uploadPath: summaries

    upload:
      https:
        url: someserver.com/upload
        auth:
          basic:
            username: user
            password: password
          headers:
            X-Auth-Token: token
