// Code generated by "stringer -type=ArtifactType -linecomment -output=artifacttype_string.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArtifactTypeBF2Demo-0]
	_ = x[ArtifactTypePRDemo-1]
	_ = x[ArtifactTypeSummary-2]
}

const _ArtifactType_name = "bf2demoprdemosummary"

var _ArtifactType_index = [...]uint8{0, 7, 13, 20}

func (i ArtifactType) String() string {
	if i < 0 || i >= ArtifactType(len(_ArtifactType_index)-1) {
		return "ArtifactType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArtifactType_name[_ArtifactType_index[i]:_ArtifactType_index[i+1]]
}
